# Generated by Django 4.2.6 on 2023-11-07 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'Task status with such Name already exist.'}, help_text='Required 255 characters or fewer.', max_length=255, unique=True, verbose_name='name'),
        ),
    ]
