# Generated by Django 4.2.7 on 2023-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_status_created_at_alter_status_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'Status with such name already exist.'}, help_text='Required 255 characters or fewer.', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
