# Generated by Django 4.2.6 on 2023-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_label_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='label.label'),
        ),
    ]
