# Generated by Django 4.2.6 on 2023-11-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_label_created_at_label_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='task',
        ),
    ]
