# Generated by Django 4.2.7 on 2023-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_label_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(error_messages={'unique': 'Label with such name already exist.'}, help_text='Required 255 characters or fewer.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='label',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
